spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fangsea_io?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 6000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      #mybatis-plus.typeAliasesPackage=io.fangsea.user.service.domain.entity
      #mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  application:
    name: auth-server
mybatis-plus:
  typeAliasesPackage: io.fangsea.user.service.domain.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
pagehelper:
  helperDialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #设置dialect分页无效,应该设置helperDialect
  #dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  page-size-zero: true
  offset-as-page-num: true
  row-bounds-with-count: true
  #dialect-alias: com.github.pagehelper.dialect.helper.MySqlDialect
logging:
  level:
    com.decorate.mapper : debug
server:
  port: 9999
  #servlet:
  #  context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#oauth2 资源服务器--账号密码正确,同意授权-->授权服务器 获得token-->访问client
system:
  #客户端配置
  client:
    clients[0]:
      clientId: app
      clientSecret: 123456
    clients[1]:
      clientId: demo
      clientSecret: 123456
    clients[2]:
      clientId: test
      clientSecret: 123456
